# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

  variables:
    MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
    MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m'

jobs:
- job: build
  displayName: Maven build
  strategy:
    matrix:
      Spark30112:
        MAVEN_PROFILE: 'apache-3.0.1_2.12'
        DEPLOY_PROFILE: 'true'
        SCALA_VERSION: '2.12'
      Spark31112:
        MAVEN_PROFILE: 'apache-3.1.1_2.12'
        DEPLOY_PROFILE: 'false'
        SCALA_VERSION: '2.12'
    maxParallel: 5
  steps:
  - task: Bash@3
    inputs:
      targetType: filePath
      filePath: dev/change-scala-version.sh
      arguments: "$(SCALA_VERSION)"
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml | "$(MAVEN_PROFILE)"'
      path: $(MAVEN_CACHE_FOLDER)
    displayName: Cache Maven local repo
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'verify -P$(MAVEN_PROFILE) -U'
